name: Demo app

on:
  workflow_run:
    workflows: ["Package"]
    branches: [master]
    types:
      - completed
jobs:
  demo-test:
    name: "Test the demo app"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: demo/package-lock.json
      - run: npm ci --prefix lib
      - run: npm run build --prefix lib
      - run: npm ci --prefix demo
      - run: cd lib && npm link && cd ..
      - run: cd demo && npm link shadows-js && cd ..
      - run: npm run build --if-present --prefix demo
      - run: npm test --prefix demo
  demo-deploy:
    name: "Deploy the demo app"
    needs:
      - demo-test
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: npm ci --prefix lib
      - run: npm run build --prefix lib
      - run: npm ci --prefix demo
      - run: cd lib && npm link && cd ..
      - run: cd demo && npm link shadows-js && cd ..
      - run: npm run build --prefix demo

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: demo/build
